### ISSUE TITLE
Support for notify.html5 component

### ISSUE THREAD

**Issue by kenthua** [lroguet/rpi-home-assistant#10]
Would it be possible to add support for the [notify.html5](https://home-assistant.io/components/notify.html5/) component for push notifications?

The requirements list `pywebpush`, but this python package requires OS packages: `libffi-dev`, `libpython-dev` and `libssl-dev`.  As a quick test in the docker container I tried an apt-get on the pre-requisite lib packages and they were not available, i.e. 

```
root@rpi2:/etc/apt/sources.list.d# apt-get install libffi-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libffi-dev
```

So an additional repos or tweaks may need to be made?  I'm not sure.  I don't see them in the main repo: http://archive.raspbian.org/raspbian/pool/main/

**Comment by lroguet** [comment]
@kenthua - The package is available, you just need to perform a `apt-get update` before the `apt-get install libffi-dev`.

```
root@black-pearl:/# apt-get install libffi-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  libffi-dev
0 upgraded, 1 newly installed, 0 to remove and 22 not upgraded.
```

Can you try and confirm it is the only package missing? I read [here](https://community.home-assistant.io/t/new-html5-component-installation/3335) `pywebpush` also requires `libpython-dev` and `libssl-dev` and I'd rather update the image with what it requires. Not more, not less.

**Comment by kenthua** [comment]
All 3 listed are required, I only put `libffi-dev` as an example.

**Comment by lroguet** [comment]
@kenthua - 0.41.0 (also latest) pushed again with the packages you needed for `notify.html5`. Let me know.
