### ISSUE TITLE
Enable Z-Wave support 

### ISSUE THREAD

**Issue by schmic** [lroguet/rpi-home-assistant#11]
Hi,

to enable Z-Wave support from HA version 0.47.0 please add "libudev-dev" to the packages.

After that you can enable Z-Wave in the configuration and it downloads the needed packages via pip.

Cheers.

PS: tested on my Pi, works like a charm

**Comment by lroguet** [comment]
Thanks @schmic. I have now pushed both 0.47.0 and 0.47.1 with the mentioned missing package for Z-Wave.
