### ISSUE TITLE
Support for Bluetooth Tracker component

### ISSUE THREAD

**Issue by uyorum** [lroguet/rpi-home-assistant#14]
[Bluetooth Tracker](https://home-assistant.io/components/device_tracker.bluetooth_tracker/) component is not working.
I think it requires `bluetooth` and `libbluetooth-dev` packages (see: https://github.com/home-assistant/home-assistant/pull/3423). Would it possible to add these packages to the image?

**Comment by lroguet** [comment]
@uyorum - Would you mind pulling `lroguet/rpi-home-assistant:latest-bt` which has Home Assistant 0.50.2 with the packages you mentioned and tell me whether or not the `Bluetooth Tracker` component works?

**Comment by uyorum** [comment]
Thank you for your work! I tried the image and it works well. It recognizes the both of online and offline of a bluetooth device.

My environment:

``` shell
$ cat /etc/issue
Raspbian GNU/Linux 8 \n \l
$ cat /etc/debian_version
8.0
$ docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:30:54 2017
 OS/Arch:      linux/arm

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:30:54 2017
 OS/Arch:      linux/arm
 Experimental: false
```

Command: `docker run -d --name hass-bt --net=host lroguet/rpi-home-assistant:latest-bt`

Tested with built-in bluetooth adapter on RaspberryPi 3B
