### ISSUE TITLE
Update package list for Ikea Trådfri setup to work

### ISSUE THREAD

**Issue by tynor88** [lroguet/rpi-home-assistant#17]
Hi,

I was not able to install _autoconf_, which is required for Ikea Trådfri setup ([see notes](https://home-assistant.io/components/tradfri/)).

Could you please upgrade the package list in the container, and also install autoconf?

I circumvented it by doing:
`sudo apt-get update`
`sudo apt-get install autoconf`

**Comment by lroguet** [comment]
I added the `autoconf` package and pushed a fresh lroguet/rpi-home-assistant:0.58.1 (or lroguet/rpi-home-assistant:latest) build. Let me know if all works as expected.

**Comment by tynor88** [comment]
Thanks alot. It works 👍
