### ISSUE TITLE
No module named hass_frontend

### ISSUE THREAD

**Issue by grleblanc** [lroguet/rpi-home-assistant#18]
Hi! I am having an issue using this container on my Pi Swarm Cluster. I can provision the container just fine but the Web Interface never starts. I am getting the follow error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/setup.py", line 190, in _async_setup_component
    result = yield from component.async_setup(hass, processed_config)
  File "/usr/local/lib/python3.5/dist-packages/homeassistant/components/frontend/__init__.py", line 313, in async_setup
    import hass_frontend
ImportError: No module named 'hass_frontend'
2017-12-10 21:07:02 WARNING (MainThread) [homeassistant.setup] Setup of recorder is taking over 10 seconds.
/config/home-assistant.log (END)
```

**Created the service:** 
`docker service create --name="home-assistant" lroguet/rpi-home-assistant:latest`

**Verify that the service is up:**
`sudo docker service ls`
`1g12wvgy5w8u        home-assistant      replicated          1/1                 lroguet/rpi-home-assistant:latest`

Any ideas? I can exec bash inside the container and manually run `hass` but I cannot figure out why it doesn't work on it's own.

**Comment by ViViDboarder** [comment]
I've had this happen because install thread timed out. Usually restarting will eventually work.

**Comment by DeviousPenguin** [comment]
Thanks, I had the same issue, I tried many things and a simple `docker restart hass` worked for me in the end.
