### ISSUE TITLE
Raspberry Pi Camera

### ISSUE THREAD

**Issue by philharle** [lroguet/rpi-home-assistant#20]
I'm attempting to get the RPi camera to work with this docker image. I've attempted to connect volumes for raspistill and /opt/vc/lib/ into the container, then running ldconfig which kinda works but is a bit clunky.
I'm wondering if including libraspberrypi-bin in the 'apt-get install' block would simplify this process?

**Comment by lroguet** [comment]
@philharle Did you try to extend the Docker image and install that package?

**Comment by philharle** [comment]
@lroguet Yeah, I did build a new image with the package and it stopped the error from occurring. However I discovered some further issues preventing the Docker container from being able to access the Pi camera and I ran out of time trying to debug it. I plan to revisit this at a later date, in the meantime it might be worth closing off the issue until I work it out.

**Comment by lroguet** [comment]
@philharle We'll reopen an issue later then.
