### ISSUE TITLE
Suggestion: Upgrade Python to 3.6.5

### ISSUE THREAD

**Issue by RodrigoTomeES** [lroguet/rpi-home-assistant#23]
Home Assistant will be required Python 3.6 so I think is a good idea upgrade to Python 3.6 before we get caught by the bull.

You can find information on how to update Python 3.6 here https://gist.github.com/dschep/24aa61672a2092246eaca2824400d37f

**Comment by lroguet** [comment]
Should/could me move to another base image instead? Do you have any recommendation?

**Comment by tynor88** [comment]
Maybe look at the official rpi3 docker image. They have migrated to latest python: https://hub.docker.com/r/homeassistant/raspberrypi3-homeassistant

**Comment by RodrigoTomeES** [comment]
Thanks, tynor88, I will try the official rpi3 docker image, I didn't know that it existed. Iroguet you can try the official image

**Comment by lroguet** [comment]
@RodrigoTomeES To be honest, I don't even run HASS anymore ;-)

**Comment by tynor88** [comment]
I tried it by switching to the image and cleaning **deps** folder. Works fine. Only thing missing is that they don't provide a "latest" tag like @lroguet does. Latest tag makes it useful for auto updating the container with https://github.com/v2tec/watchtower

**Comment by RodrigoTomeES** [comment]
Yes, I also saw that, I think we should be open a discussion in the forum.

**Comment by wburgers** [comment]
Sorry to be late to the party.
I pulled the homeassistant/raspberrypi2-homeassistant image (on my rpi2)
It is more than 1GB in size, whereas the image by @lroguet is "only" 500 MB.
So I rather use this one.
Though I notice that it has not been updating properly recently.

**Comment by lroguet** [comment]
Builds are failing since 0.82.0 and I haven't had the time to investigate.

**Comment by wburgers** [comment]
I downloaded this repo and ran the build.sh script recently.
The first build for 0.82.1 did not work on my pi, but when I tried again, it did work.
The script still puts the latest version number in /var/log... even if the build failed.
So removing that file and restarting the build should work ;)

**Comment by lroguet** [comment]
@wburgers - Indeed. Need to fail the build completely and not update the version file in those cases.

**Comment by wburgers** [comment]
Home Assistant will drop support for python 3.5 next month.
"Python 3.5 support is deprecated and will be removed in the first release after August 1. Please upgrade Python."

Are you still using this image yourself @lroguet?

**Comment by lroguet** [comment]
@wburgers I haven't used HA in more than a year but will fix this. Unless someone is kind enough to send a PR my way of contribute to this repository long term (even better).

**Comment by scottsweb** [comment]
There might be a simple solution to this. It looks like Buster uses Python 3.7.3 so switching release in the build script could be all we need:

https://github.com/lroguet/rpi-home-assistant/blob/master/build.sh#L5

**Comment by lroguet** [comment]
@scottsweb Just pushed lroguet/rpi-home-assistant:0.97.2-exp based on buster. I've tested it myself and it ran fine with no errors.

**Comment by scottsweb** [comment]
Just tested `latest/0.97.2` and all seems to be well. Thank you @lroguet
