### ISSUE TITLE
Latest version: 0.68.0b0 not published?

### ISSUE THREAD

**Issue by tynor88** [lroguet/rpi-home-assistant#25]
Can you trigger it please 😀

**Comment by trebolcinco** [comment]
Could we also get 67.1?

**Comment by lroguet** [comment]
The project JSON description was moved from `https://pypi.python.org/pypi/homeassistant/json` to `https://pypi.org/pypi/homeassistant/json` which made the `build.sh` script unable to figure out what the current of HASS version was.

Building 0.67.1 now. 0.68.0b0 next.
