### ISSUE TITLE
SSH seems to be missing or isn't running

### ISSUE THREAD

**Issue by DeviousPenguin** [lroguet/rpi-home-assistant#3]
I'm trying do get device tracking working on my network, and it seems to be getting a problem with SSH, here's the output from my home-assistant.log, I'm trying to use my router to track devices and home-assistant talks to the router over SSH.

> 16-10-20 21:12:59 homeassistant.components.device_tracker: Error setting up platform asuswrt
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/device_tracker/**init**.py", line 139, in setup_platform
>     scanner = platform.get_scanner(hass, {DOMAIN: p_config})
>   File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/device_tracker/asuswrt.py", line 83, in get_scanner
>     scanner = AsusWrtDeviceScanner(config[DOMAIN])
>   File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/device_tracker/asuswrt.py", line 125, in **init**
>     data = self.get_asuswrt_data()
>   File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/device_tracker/asuswrt.py", line 241, in get_asuswrt_data
>     result = self.ssh_connection()
>   File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/device_tracker/asuswrt.py", line 170, in ssh_connection
>     ssh.login(self.host, self.username, **self.ssh_secret)
>   File "/config/deps/pexpect/pxssh.py", line 279, in login
>     spawn._spawn(self, cmd)
>   File "/config/deps/pexpect/pty_spawn.py", line 267, in _spawn
>     'executable: %s.' % self.command)
> pexpect.exceptions.ExceptionPexpect: The command was not found or was not executable: ssh.

However Raspbian includes SSH so could this be a permissions issue? It would be good to fix it as I'm sure others will also want to use their router for device tracking.

EDIT: If you want to reproduce the error try adding the device_tracker.asuswrt section to your configuration, just put in any IP address for the router. It should still show the error even if you don't have an Asus router.

**Comment by lroguet** [comment]
SSH added and pushed with the '0.30.2' and 'latest' tags.
