### ISSUE TITLE
Z-wave OOTB compatibiltiy

### ISSUE THREAD

**Issue by EugenMayer** [lroguet/rpi-home-assistant#4]
Since i have z rpi + razberry controller, i am very interested in a z-wave extension for this docker image. I am doing Docker a lot myself, so i might be able to help - the problem is, i am a bloody started with z-wave and already struggled with some oddness on rpi + raspberrian + openhab/z-way.

Are you interested in joining forces here? If you like, we could also have a chat at gitter. You find me at https://gitter.im/EugenMayer/docker-sync or simply give me a pm whatever. Thank you!

**Comment by lroguet** [comment]
Won't fix (no z-wave hardware available).
