### ISSUE TITLE
sock.sendto permisison error

### ISSUE THREAD

**Issue by stoutouloutou** [lroguet/rpi-home-assistant#7]
Hello,
I get an error while running this docker image on my Pi, the log file show:

> PermissionError: [Errno 1] Operation not permitted
> 17-03-08 14:59:55 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>  File "/usr/lib/python3.4/asyncio/tasks.py", line 233, in _step
>     result = coro.throw(exc)
>   File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/discovery.py", line 110, in scan_devices
>     None, _discover, netdisco)
>   File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
>     yield self  # This tells Task to wait for completion.
>   File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
>     value = future.result()
>   File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
>     raise self._exception
>   File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/discovery.py", line 127, in _discover
>     netdisco.scan()
>   File "/config/deps/netdisco/discovery.py", line 62, in scan
>     self.gdm.scan()
>   File "/config/deps/netdisco/gdm.py", line 21, in scan
>     self.update()
>   File "/config/deps/netdisco/gdm.py", line 76, in update
>     sock.sendto(gdm_msg, (gdm_ip, gdm_port))
> PermissionError: [Errno 1] Operation not permitted

I ran the docker command as shown, with --net=host parameter, and couldn't find any help on forums...
Would anyone have ideas how to solve this problem ?
Thank you !

**Comment by stoutouloutou** [comment]
I found the problem, without solving it yet:
it has nothing to do specifically with this image, but it's a firewall problem: my iptables rules do not alllow this traffic, it works when I desactivate it.

**Comment by lroguet** [comment]
Glad you found the issue.
