### ISSUE TITLE
ping not installed

### ISSUE THREAD

**Issue by kenthua** [lroguet/rpi-home-assistant#8]
would it be possible to install iptutils (ping) into the docker image?  the home-assistant WOL feature uses "ping"

**Comment by lroguet** [comment]
@kenthua - Could you try with the new 0.40.0 image I just pushed (`docker pull lroguet/rpi-home-assistant:0.40.0`)?

**Comment by kenthua** [comment]
Yes this was on 0.40.0 earlier today, unless you pushed a new one recently.

**Comment by lroguet** [comment]
@kenthua - The current 0.40.0 has 'ping' installed. I pushed a new one.

**Comment by kenthua** [comment]
@lroguet thanks! all good now.
