### ISSUE TITLE
Systemctl and update

### ISSUE THREAD

**Issue by derechtedude** [lroguet/rpi-home-assistant#9]
No issue rather me being too stupid to do it.
How do I update to the new version?
How do I enable systemctl. Can't get this to work. Tried to follow the setup in Hass tutorial

Thanks in advance

**Comment by lroguet** [comment]
@derechtedude 
To update to the latest version just stop your existing container (`docker stop hass` then`docker rm hass` where `hass` is the name of your Home Assistant container) and start a new one (`docker run -d --name hass --net=host -v /etc/localtime:/etc/localtime:ro -v /home/pi/home-assistant/configuration:/config lroguet/rpi-home-assistant:latest` for example).

Regarding systemctl I'm not sure which setup instruction you're referring to. Are you trying to enable systemctl on your host or inside your Home Assistant Docker container?

**Comment by derechtedude** [comment]
@lroguet 
Thank you for the Infos how to update. This is a complete reinstall right?
Therefore I won't do that for small updates as I would have to reconfig everything again.
I tried this tutorial for systemd commands:
https://home-assistant.io/docs/autostart/systemd/
used the docker template service file
and exchanged your one line command with the one in the file.

I did that directly under root. I am not familiar with docker as I just use it as a workaround to use Hass on my OSMC Raspberry Pi, as I cannot get my Harmony Hub running under OSMC Hass Venv.
Other than the autostart everything runs really nicely!

**Comment by lroguet** [comment]
@derechtedude - Well, if you have your configuration file(s) persisted on the host file system (see the instructions) it does not matter if you stop the current container and start a new one. Configuration will then survive the restart.

**Comment by derechtedude** [comment]
thanks, for the tip. Ok updating was no issue! Haven't tried systemctl anymore as my pi runs rather stable atm. therefore was not necessary ;-)

**Comment by ronnicek** [comment]
Hi, there is a new version (0.49) and I restarted hass container (with rm of it) but I have still 0.48.1 version. Any ideas? :)

**Comment by lroguet** [comment]
@ronnicek - Your issue doesn't have much to do with `Systemctl`. What command(s) are you using to start your `hass` container?

I suggest you try `docker pull lroguet/rpi-home-assistant` before the `docker run` command.

**Comment by ronnicek** [comment]
@lroguet no :) but issue was also about update.. so just asking.. and answer in https://github.com/lroguet/rpi-home-assistant/issues/9#issuecomment-288495774 doesnt say anything about pulling again.. I was wondering how that works :)

I have it in docker-compose.yml :)
